version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        networks:
            - my-network
        environment:
            docker: "true"
        ports:
            - 8081:8081
        volumes:
            - .:/var/www
            - logs:/var/www/logs
